name: e2e

on: push

permissions:
  contents: write

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Release
        uses: softprops/action-gh-release@master
        if: github.ref_type == 'tag'
        with:
          files: |
            test-assets/release-notes.md
            test-assets/sample-asset.txt
